### ISSUE TITLE
Deleting tabs bug

### ISSUE THREAD

**Issue by bradgowland** [WebAudioBoys/tbd-2#19]
When one user deletes a tab to the left of the tab you are on, your tab will change because of underlying tab indices are shifted.

Example: There are three tabs: `tab 1`, `tab 2`, and `tab 3`. If I am on `tab 3` and Dave deletes `tab 1`, I will be shifted to `tab 2`. This is because the tabs are displayed based on the indices of an array, and splicing out an element from earlier in the array changes the tab that I see displayed.

**Comment by DaveVanDusen** [comment]
I think that I slammed this. Basically clicking the x was toggling the tabs which created some confusion when the message was relayed back to the client. I'll wait to test with multiple clients before I close this comment...
