### ISSUE TITLE
Option to load page with presets in place

### ISSUE THREAD

**Issue by bradgowland** [WebAudioBoys/tbd-2#26]
Should we have an option to start the session with multiple tabs open and properly configured to send midi without any user work?

Ex: Three tabs, bass, drums, chords, with preselected MIDI out channels. Correlates with channels pre-picked in hosted DAW templates.

**Comment by DaveVanDusen** [comment]
I like this idea and should be no problem to get going although it makes sense to put together all of our templates in the DAWs. I think that it will be smart to add some kind of first steps menu for users who arrive at the root url...

**Comment by bradgowland** [comment]
all done
